apiVersion: v1
kind: Service
metadata:
  name: lanches-api-service
spec:
  selector:
    app: lanches-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort